sudo: required
language: php

php:
  - 7.3

git:
  depth: 1

services:
- docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
  matrix:
    - COMPOSER_BOUNDARY=lowest
    - COMPOSER_BOUNDARY=highest


before_install:
  - 'docker-compose up -d'

install:
  - 'docker-compose exec web composer install  --ansi --no-suggest --no-progress'
  - '[[ ${COMPOSER_BOUNDARY} != "lowest" ]] || docker-compose exec web composer update --prefer-lowest --ansi --no-suggest --no-progress'
  - 'docker-compose exec web chown -R www-data:www-data build'

before_script:
  - 'docker-compose exec web ./vendor/bin/run drupal:site-install'
  - 'docker-compose exec web chmod -R 775 build/sites/default'

script:
  - 'docker-compose exec web ./vendor/bin/grumphp run'
  - 'docker-compose exec web ./vendor/bin/behat --strict'

notifications:
  email: false