sudo: required
language: php

php:
  - 7.3

git:
  depth: 1

services:
- docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0

before_install:
  - docker-compose up -d

install:
  - docker-compose exec web composer install
  - docker-compose exec web chown -R www-data:www-data build

before_script:
  - docker-compose exec web ./vendor/bin/run drupal:site-install
  - docker-compose exec web chmod -R 775 build/sites/default

script:
  - docker-compose exec web ./vendor/bin/grump run
  - docker-compose exec web ./vendor/bin/behat --strict

notifications:
  email: false