version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:7.3
    working_dir: /var/www/html
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_host=${DOCKER_HOST_IP} remote_port=9000 idekey=PHPSTORM remote_autostart=1"
      PHP_IDE_CONFIG: "serverName=Test"
  mysql:
    image: percona/percona-server:5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  selenium:
    image: selenium/standalone-chrome-debug:3.11
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
    ports:
      - "5900:5900"
    expose:
      - '4444'
